/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iRXBuLSA8k8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Syne } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function paymentSection() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4">
        <div className="container mx-auto flex justify-between items-center">
          <div className="text-xl font-bold">AURA DIGITAL LABS</div>
        </div>
      </header>
      <div className="flex items-center justify-center bg-background p-4 md:p-6 flex-1">
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle>Payment Details</CardTitle>
            <CardDescription>Review and update your payment information.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-1">
              <Label htmlFor="name">Account Name</Label>
              <Input id="name" defaultValue="John Doe" />
            </div>
            <div className="grid gap-1">
              <Label htmlFor="branch">Account Branch</Label>
              <Input id="branch" defaultValue="Main Street" />
            </div>
            <div className="grid gap-1">
              <Label htmlFor="bank">Bank Name</Label>
              <Input id="bank" defaultValue="Acme Bank" />
            </div>
            <div className="grid gap-1">
              <Label htmlFor="number">Account Number</Label>
              <Input id="number" defaultValue="123456789" />
            </div>
          </CardContent>
          <CardFooter className="flex justify-end gap-2">
            <Button variant="outline">Cancel</Button>
            <Button>Save Changes</Button>
          </CardFooter>
        </Card>
      </div>
      <footer className="bg-primary text-primary-foreground py-4">
        <div className="container mx-auto flex justify-center">
          <div className="text-sm">© 2023 AURA DIGITAL LABS. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}
